#TF SYNTAX BASICS

In [8]:
import tensorflow as tf
from tensorflow.compat.v1 import Session

In [9]:
print(tf.__version__)

2.1.0


In [10]:
hello = tf.constant(5.0)

In [11]:
world = tf.constant(6.0)

In [12]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [13]:
print(hello)
c = tf.math.add(hello,world)

tf.Tensor(5.0, shape=(), dtype=float32)


In [14]:
print(c)


tf.Tensor(11.0, shape=(), dtype=float32)


In [15]:
from tensorflow.python.framework.ops import disable_eager_execution

disable_eager_execution()

c = tf.constant(7.0)
d = tf.constant(9.0)
e = c * d
sess = Session()
# with sess.as_default():
#     assert tf.compat.v1.get_default_session() is sess
#     print(e.eval())
a = sess.run(e)
print(a)

63.0


In [17]:
from tensorflow.python.framework.ops import disable_eager_execution

disable_eager_execution()

c = tf.constant("Hello")
d = tf.constant("world")
e = c + d
sess = Session()
# with sess.as_default():
#     assert tf.compat.v1.get_default_session() is sess
#     print(e.eval())
a = sess.run(e)
print(a)

b'Helloworld'


In [18]:
a = tf.constant(10)
b = tf.constant(20)

In [19]:
a+b


<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [20]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [21]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [22]:
const = tf.constant(20)

In [23]:
fill_mat = tf.fill((4,4),10)

In [24]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))

In [27]:
myrandn = tf.random.normal((4,4),mean=0,stddev=1.0)

In [28]:
myrandu = tf.random.uniform((4,4),minval=0,maxval=1)

In [29]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [30]:
myones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [31]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [33]:
sess = tf.compat.v1.InteractiveSession()

In [36]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

20


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.18785524 -1.0318394  -0.22294633  0.2965671 ]
 [ 1.0951658  -1.0144377  -0.70078975 -0.7127743 ]
 [ 0.07617147  0.30719706  0.98845327  0.32636434]
 [ 0.7913249   1.0100962   0.2040168  -0.57920665]]


[[0.93703747 0.19138706 0.6094017  0.20696104]
 [0.61192393 0.07256162 0.72058153 0.5598482 ]
 [0.08510244 0.12449312 0.7718129  0.50714934]
 [0.12251961 0.43685472 0.0574981  0.08522868]]




In [37]:
for op in my_ops:
    print(op.eval())
    print("\n")

20


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.9824334   1.0147084   0.02368155 -0.23043796]
 [-2.0262005  -0.07320838  1.2125039  -0.5933553 ]
 [ 2.1902025   0.62522465 -0.5096558   0.6749295 ]
 [ 0.78371274  0.27332297 -0.49390972  0.8678254 ]]


[[0.52976894 0.8790816  0.84314764 0.4164145 ]
 [0.19228375 0.764814   0.24422729 0.6134864 ]
 [0.38720727 0.82759833 0.44638705 0.4167905 ]
 [0.98924387 0.9523009  0.88029814 0.6415423 ]]




In [40]:
a = tf.constant([[1,2],[3,4]])

In [41]:
a.get_shape()

TensorShape([2, 2])

In [42]:
b = tf.constant([[10],[100]])

In [43]:
b.get_shape()

TensorShape([2, 1])

In [44]:
result = tf.matmul(a,b)

In [45]:
sess.run(result)

array([[210],
       [430]])

In [46]:
result.eval()

array([[210],
       [430]])